version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - NODE_ENV=production
    networks:
      - pandai-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - pandai-network

  # Optional: Database service (uncomment if needed)
  # database:
  #   image: postgres:14-alpine
  #   environment:
  #     POSTGRES_DB: pandai_games
  #     POSTGRES_USER: pandai
  #     POSTGRES_PASSWORD: your_password_here
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - pandai-network

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - pandai-network

networks:
  pandai-network:
    driver: bridge

volumes:
  postgres_data:
